development:
  task_seeder:
    class: TaskProducerJob
    queue: default
    schedule: every 2 minutes

production:
  task_seeder:
    class: TaskProducerJob
    queue: default
    schedule: every 2 minutes
